"""
pipeline/nodes/github_push_node.py
GitHub auto-push node for The Forge build pipeline.

After packaging is complete, this node optionally pushes all generated files
to a GitHub repository. If push_to_github is False or GITHUB_TOKEN is not set,
the node is a no-op and returns state unchanged.

Uses PyGithub (synchronous) wrapped in asyncio executor calls so the async
pipeline is never blocked.

Push strategy:
  - Check if the repo already exists for the authenticated user.
  - If not, create a new private repo with that name.
  - For each generated file, create or update via the Contents API.
  - Commit message: "Generated by The Forge".
  - On any failure: log error, set github_push_status="failed", return state.
    Never raises — build success is never dependent on push success.
"""

import asyncio
from typing import TYPE_CHECKING

from loguru import logger
from sqlalchemy import update

from config.settings import settings
from memory.database import get_session
from memory.models import ForgeRun

if TYPE_CHECKING:
    from pipeline.pipeline import PipelineState


async def github_push_node(state: "PipelineState") -> "PipelineState":
    """
    Push all generated files to GitHub. Optional — never fails the build.

    Args:
        state: PipelineState with generated_files populated by codegen/package nodes.

    Returns:
        state with github_repo_url set (if push succeeded).
    """
    if not state.push_to_github:
        logger.info(f"[{state.run_id}] GitHub push disabled for this run — skipping")
        return state

    if not settings.github_token:
        logger.warning(
            f"[{state.run_id}] GITHUB_TOKEN not set — skipping GitHub push"
        )
        return state

    if not state.generated_files:
        logger.warning(
            f"[{state.run_id}] No generated files to push — skipping GitHub push"
        )
        return state

    logger.info(
        f"[{state.run_id}] Starting GitHub push — "
        f"repo={state.repo_name} files={len(state.generated_files)}"
    )

    try:
        repo_url, push_status = await _push_to_github(state)
    except Exception as exc:
        logger.error(f"[{state.run_id}] GitHub push failed unexpectedly: {exc}")
        repo_url = None
        push_status = "failed"

    # Persist result to DB (fire and forget — never raise)
    try:
        async with get_session() as session:
            values: dict = {"github_push_status": push_status}
            if repo_url:
                values["github_repo_url"] = repo_url
            await session.execute(
                update(ForgeRun)
                .where(ForgeRun.run_id == state.run_id)
                .values(**values)
            )
        logger.info(
            f"[{state.run_id}] GitHub push status saved: "
            f"status={push_status} url={repo_url}"
        )
    except Exception as db_exc:
        logger.error(
            f"[{state.run_id}] Failed to save GitHub push status to DB: {db_exc}"
        )

    # Send Telegram notification
    try:
        from app.api.services.notify import _send

        if push_status == "success" and repo_url:
            await _send(
                f"<b>The Forge — GitHub Push Complete</b>\n\n"
                f"<b>{state.title}</b>\n"
                f"Run ID: <code>{state.run_id}</code>\n\n"
                f"Repository: <a href='{repo_url}'>{repo_url}</a>\n"
                f"Files pushed: <b>{len(state.generated_files)}</b>"
            )
        elif push_status == "failed":
            await _send(
                f"<b>The Forge — GitHub Push Failed</b>\n\n"
                f"<b>{state.title}</b>\n"
                f"Run ID: <code>{state.run_id}</code>\n\n"
                "The build package is still available for download. "
                "Check GITHUB_TOKEN permissions and retry manually."
            )
    except Exception as notify_exc:
        logger.error(
            f"[{state.run_id}] GitHub push notification failed (non-blocking): {notify_exc}"
        )

    return state


async def _push_to_github(state: "PipelineState") -> tuple[str, str]:
    """
    Core GitHub push logic. Runs sync PyGithub calls in executor.

    Returns:
        (repo_html_url, push_status) where push_status is "success" or "failed".
    """
    from github import Github, GithubException

    loop = asyncio.get_event_loop()

    # Derive repo name from state or spec
    repo_name = state.repo_name
    if not repo_name and state.spec:
        repo_name = state.spec.get("agent_slug", "")
    if not repo_name:
        repo_name = _slugify(state.title)

    logger.info(f"[{state.run_id}] GitHub target repo: {repo_name}")

    # Create GitHub client
    g = Github(settings.github_token)

    # Get or create repository
    try:
        repo = await loop.run_in_executor(
            None, lambda: g.get_user().get_repo(repo_name)
        )
        logger.info(f"[{state.run_id}] Using existing GitHub repo: {repo.html_url}")
    except GithubException as get_exc:
        if get_exc.status == 404:
            logger.info(
                f"[{state.run_id}] Repo '{repo_name}' not found — creating new private repo"
            )
            try:
                repo = await loop.run_in_executor(
                    None,
                    lambda: g.get_user().create_repo(
                        name=repo_name,
                        description=f"Generated by The Forge — {state.title}",
                        private=True,
                        auto_init=False,
                    ),
                )
                logger.info(
                    f"[{state.run_id}] Created new repo: {repo.html_url}"
                )
            except GithubException as create_exc:
                logger.error(
                    f"[{state.run_id}] Failed to create GitHub repo '{repo_name}': "
                    f"status={create_exc.status} data={create_exc.data}"
                )
                return ("", "failed")
        else:
            logger.error(
                f"[{state.run_id}] GitHub API error fetching repo '{repo_name}': "
                f"status={get_exc.status} data={get_exc.data}"
            )
            return ("", "failed")

    repo_url = repo.html_url
    commit_message = "Generated by The Forge"

    # Push all generated files
    files_pushed = 0
    files_errored = 0

    for file_path, content in state.generated_files.items():
        try:
            # Normalise path — remove leading slash
            normalised_path = file_path.lstrip("/")
            encoded_content = content.encode("utf-8")

            # Check if the file already exists to get its SHA for update
            try:
                existing = await loop.run_in_executor(
                    None, lambda p=normalised_path: repo.get_contents(p)
                )
                existing_sha = existing.sha if not isinstance(existing, list) else existing[0].sha
                await loop.run_in_executor(
                    None,
                    lambda p=normalised_path, c=encoded_content, s=existing_sha: repo.update_file(
                        path=p,
                        message=commit_message,
                        content=c,
                        sha=s,
                        branch="main",
                    ),
                )
                logger.debug(
                    f"[{state.run_id}] Updated: {normalised_path}"
                )
            except GithubException as contents_exc:
                if contents_exc.status == 404:
                    # File does not exist — create it
                    await loop.run_in_executor(
                        None,
                        lambda p=normalised_path, c=encoded_content: repo.create_file(
                            path=p,
                            message=commit_message,
                            content=c,
                            branch="main",
                        ),
                    )
                    logger.debug(
                        f"[{state.run_id}] Created: {normalised_path}"
                    )
                else:
                    raise

            files_pushed += 1

        except Exception as file_exc:
            logger.error(
                f"[{state.run_id}] Failed to push file '{file_path}': {file_exc}"
            )
            files_errored += 1

    logger.info(
        f"[{state.run_id}] GitHub push complete — "
        f"pushed={files_pushed} errors={files_errored} repo={repo_url}"
    )

    push_status = "success" if files_errored == 0 else "partial"
    if files_pushed == 0 and files_errored > 0:
        push_status = "failed"

    return (repo_url, push_status)


def _slugify(text: str) -> str:
    """Convert a title string to a valid GitHub repository name (kebab-case)."""
    import re

    slug = text.lower().strip()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    slug = slug.strip("-")
    # GitHub repo names max 100 chars
    return slug[:100] or "forge-build"
