import { useState } from "react";

const PIPELINE_STAGES = [
  {
    icon: "📋",
    label: "Blueprint Submission",
    description: "User submits blueprint text or uploads a .docx/.pdf file",
    detail: "Accepts free-form text, structured documents, or template-based blueprints. Stored in forge_runs table.",
    color: "border-purple-800 bg-purple-950/10",
    badge: "bg-purple-900/50 text-purple-300",
  },
  {
    icon: "✅",
    label: "Validation",
    description: "Claude Haiku checks blueprint completeness (< 5s)",
    detail: "Fast sanity check: is this a real agent spec? Does it describe services, a purpose, user interactions? Rejects empty or malformed input immediately.",
    color: "border-green-800 bg-green-950/10",
    badge: "bg-green-900/50 text-green-300",
  },
  {
    icon: "🔍",
    label: "Parsing",
    description: "Claude Sonnet extracts full spec JSON: services, tables, routes, files",
    detail: "Converts prose blueprint into structured specification: agent_name, description, services[], database_tables[], api_routes[], file_list[], estimated_complexity.",
    color: "border-blue-800 bg-blue-950/10",
    badge: "bg-blue-900/50 text-blue-300",
  },
  {
    icon: "👤",
    label: "Spec Confirmation",
    description: "User reviews and approves the parsed specification",
    detail: "Parsed spec is shown in the dashboard with full detail. User can approve to proceed or reject and resubmit with corrections. Run pauses here until user acts.",
    color: "border-yellow-800 bg-yellow-950/10",
    badge: "bg-yellow-900/50 text-yellow-300",
  },
  {
    icon: "🏗️",
    label: "Architecture",
    description: "Claude Sonnet generates layered build manifest with dependency order",
    detail: "Produces the complete file list with layer assignments, import dependencies, and generation order. The manifest drives the entire code generation phase.",
    color: "border-teal-800 bg-teal-950/10",
    badge: "bg-teal-900/50 text-teal-300",
  },
  {
    icon: "⚡",
    label: "Code Generation",
    description: "6 layers generated in strict dependency order (15–20 min)",
    detail: "Each file generated by Claude Sonnet 4.6 with full context: spec, architecture manifest, already-generated files, intelligence layer, knowledge base records. Evaluator scores every file before acceptance. Failed files auto-retry up to 3 times.",
    color: "border-purple-700 bg-purple-950/20",
    badge: "bg-purple-900/50 text-purple-300",
  },
  {
    icon: "📦",
    label: "Packaging",
    description: "Formatting, security scan, verifier review, ZIP assembly",
    detail: "Black + isort run on all Python files. Bandit security scan checks for exposed secrets and insecure patterns. Verifier (second Claude instance) reviews the complete package: 'What would prevent this from deploying on first try?' ZIP assembled with all required files.",
    color: "border-cyan-800 bg-cyan-950/10",
    badge: "bg-cyan-900/50 text-cyan-300",
  },
  {
    icon: "🔄",
    label: "GitHub Push",
    description: "Repo created/updated, all files committed (if enabled)",
    detail: "Uses PyGitHub to create the repo (or push to existing). Commits all generated files in a single commit. Enables GitHub Actions CI/CD. Sets up branch protection rules.",
    color: "border-gray-700 bg-gray-800/20",
    badge: "bg-gray-800 text-gray-300",
  },
  {
    icon: "✓",
    label: "Complete",
    description: "ZIP available for download, Telegram notification sent to Jackson",
    detail: "Package stored in /tmp, presigned URL generated. Build summary logged to knowledge_base for future context. Performance metrics recorded. Telegram notification with build summary dispatched.",
    color: "border-green-700 bg-green-950/20",
    badge: "bg-green-900/50 text-green-300",
  },
];

const LAYERS = [
  {
    num: 1,
    label: "Database Schema",
    files: ["models.py", "database.py", "migrations/"],
    description: "Imported by everything — generated first. SQLAlchemy 2.0 models with pgvector support.",
    color: "text-yellow-400",
  },
  {
    num: 2,
    label: "Infrastructure",
    files: ["requirements.txt", "docker-compose.yml", "Dockerfile.api", "Dockerfile.worker", "Dockerfile.dashboard", ".env.example"],
    description: "Build and runtime config. No application logic dependencies.",
    color: "text-orange-400",
  },
  {
    num: 3,
    label: "Backend API",
    files: ["main.py", "routes/", "services/", "middleware/", "auth.py"],
    description: "FastAPI routes, services, middleware. Depends on Layer 1 models.",
    color: "text-purple-400",
  },
  {
    num: 4,
    label: "Worker / Agent Logic",
    files: ["workers/", "pipeline/", "intelligence/", "knowledge/"],
    description: "RQ workers, pipeline nodes, background processors, intelligence and knowledge engine files.",
    color: "text-teal-400",
  },
  {
    num: 5,
    label: "Web Dashboard",
    files: ["web-dashboard/src/", "web-dashboard/index.html", "web-dashboard/package.json"],
    description: "React + Vite + Tailwind. Communicates with Layer 3 API.",
    color: "text-cyan-400",
  },
  {
    num: 6,
    label: "Deployment",
    files: ["fly.toml", "fly.worker.toml", "fly.dashboard.toml", ".github/workflows/deploy.yml"],
    description: "Fly.io configuration per service, GitHub Actions auto-deploy pipeline.",
    color: "text-blue-400",
  },
  {
    num: 7,
    label: "Documentation",
    files: ["README.md", "FLY_SECRETS.txt", "connection_test.py", ".env.example"],
    description: "Complete setup guide, secrets checklist, connection verification script.",
    color: "text-gray-400",
  },
];

const INTELLIGENCE_FILES = [
  { file: "config/model_config.py", purpose: "Routes Claude calls: Sonnet/Opus for reasoning, Haiku for classification. Reduces API cost 35–40%." },
  { file: "intelligence/knowledge_base.py", purpose: "Stores outcomes from every operation, retrieves via pgvector similarity. Agent improves with every run." },
  { file: "intelligence/meta_rules.py", purpose: "Weekly job extracts operational rules from real outcomes, auto-updates prompts. Agent self-improves without code changes." },
  { file: "intelligence/context_assembler.py", purpose: "Assembles optimal context before every major Claude call: KB records + meta-rules + system state." },
  { file: "intelligence/evaluator.py", purpose: "Scores every significant output against domain rubric before delivery. Substandard outputs regenerated." },
  { file: "intelligence/verifier.py", purpose: "Independent second Claude instance adversarially reviews high-stakes outputs." },
  { file: "monitoring/performance_monitor.py", purpose: "Tracks 5 KPIs every 6 hours, detects 15%+ degradation, auto-diagnoses, alerts via Telegram." },
];

export default function PipelineTab({ isMobile = false }) {
  const [expandedStage, setExpandedStage] = useState(null);
  const [showLayers, setShowLayers] = useState(!isMobile);
  const [showIntelligence, setShowIntelligence] = useState(!isMobile);

  return (
    <div className={isMobile ? "px-2 pb-24" : "max-w-3xl mx-auto"}>
      <h2
        className={`font-['Bebas_Neue'] text-gray-100 tracking-widest mb-2 ${
          isMobile ? "text-3xl" : "text-4xl"
        }`}
      >
        PIPELINE
      </h2>
      <p className={`text-gray-500 mb-6 ${isMobile ? "text-sm" : "text-sm mb-8"}`}>
        Every build flows through these 9 stages in sequence. Tap any stage for full detail.
      </p>

      {/* Pipeline stages */}
      <div className="relative">
        {PIPELINE_STAGES.map((stage, i) => (
          <div
            key={i}
            className={`flex gap-3 mb-1 ${isMobile ? "gap-3" : "gap-4"}`}
          >
            {/* Connector column */}
            <div className="flex flex-col items-center w-10 flex-shrink-0">
              <button
                className={`w-11 h-11 min-w-[44px] min-h-[44px] rounded-xl border-2 ${stage.color} flex items-center justify-center text-lg flex-shrink-0 z-10 cursor-pointer active:scale-95 transition-transform`}
                onClick={() => setExpandedStage(expandedStage === i ? null : i)}
                aria-label={`Toggle stage ${i + 1}: ${stage.label}`}
              >
                {stage.icon}
              </button>
              {i < PIPELINE_STAGES.length - 1 && (
                <div className="flex-1 w-px bg-gray-800 my-1" style={{ minHeight: "20px" }} />
              )}
            </div>

            {/* Content */}
            <div className="flex-1 mb-2 min-w-0">
              <button
                onClick={() => setExpandedStage(expandedStage === i ? null : i)}
                className={`w-full text-left border rounded-xl transition-colors active:bg-gray-750 ${
                  isMobile ? "px-3 py-3" : "px-4 py-3"
                } ${
                  expandedStage === i
                    ? "bg-gray-800 " + stage.color
                    : "border-gray-800 bg-gray-900 hover:bg-gray-800"
                }`}
                style={{ minHeight: "44px" }}
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`text-xs px-2 py-0.5 rounded font-medium ${stage.badge}`}>
                        Stage {i + 1}
                      </span>
                    </div>
                    <p className={`text-gray-100 font-semibold ${isMobile ? "text-sm" : "text-sm"}`}>
                      {stage.label}
                    </p>
                    <p className={`text-gray-400 mt-0.5 ${isMobile ? "text-xs leading-relaxed" : "text-xs"}`}>
                      {stage.description}
                    </p>
                  </div>
                  <span className="text-gray-600 text-sm flex-shrink-0 mt-1 min-w-[20px] text-center">
                    {expandedStage === i ? "▲" : "▼"}
                  </span>
                </div>

                {expandedStage === i && (
                  <div className="mt-3 pt-3 border-t border-gray-700">
                    <p className={`text-gray-300 leading-relaxed ${isMobile ? "text-sm" : "text-sm"}`}>
                      {stage.detail}
                    </p>
                  </div>
                )}
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Code Generation Layers */}
      <div className="mt-8 border border-gray-800 rounded-xl overflow-hidden">
        <button
          onClick={() => setShowLayers(!showLayers)}
          className="w-full flex items-center justify-between px-4 py-4 bg-gray-900 hover:bg-gray-800 active:bg-gray-750 transition-colors"
          style={{ minHeight: "44px" }}
        >
          <div className="min-w-0 flex-1">
            <p className={`font-['Bebas_Neue'] text-gray-100 tracking-wider text-left ${isMobile ? "text-lg" : "text-xl"}`}>
              CODE GENERATION LAYERS
            </p>
            <p className="text-gray-500 text-xs text-left mt-0.5">
              7 layers generated in dependency order — Stage 6 detail
            </p>
          </div>
          <span className="text-gray-600 flex-shrink-0 ml-2 min-w-[20px] text-center">
            {showLayers ? "▲" : "▼"}
          </span>
        </button>

        {showLayers && (
          <div className="divide-y divide-gray-800">
            {LAYERS.map((layer) => (
              <div key={layer.num} className={isMobile ? "px-3 py-4" : "px-5 py-4"}>
                <div className={`flex items-start ${isMobile ? "gap-3" : "gap-4"}`}>
                  <div className="w-9 h-9 min-w-[36px] min-h-[36px] rounded-lg bg-gray-800 flex items-center justify-center flex-shrink-0">
                    <span className={`text-sm font-bold font-mono ${layer.color}`}>
                      {layer.num}
                    </span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className={`text-sm font-semibold ${layer.color}`}>{layer.label}</p>
                    <p className="text-gray-500 text-xs mt-0.5">{layer.description}</p>
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      {layer.files.map((f) => (
                        <span
                          key={f}
                          className={`bg-gray-800 text-gray-400 rounded font-mono ${
                            isMobile ? "px-2 py-1 text-xs" : "px-2 py-0.5 rounded text-xs"
                          }`}
                        >
                          {f}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Intelligence Layer */}
      <div className="mt-4 border border-teal-900 rounded-xl overflow-hidden">
        <button
          onClick={() => setShowIntelligence(!showIntelligence)}
          className="w-full flex items-center justify-between px-4 py-4 bg-teal-950/20 hover:bg-teal-950/30 active:bg-teal-950/40 transition-colors"
          style={{ minHeight: "44px" }}
        >
          <div className="min-w-0 flex-1">
            <p className={`font-['Bebas_Neue'] text-teal-300 tracking-wider text-left ${isMobile ? "text-lg" : "text-xl"}`}>
              INTELLIGENCE LAYER
            </p>
            <p className="text-teal-600 text-xs text-left mt-0.5">
              7 files included in every build — agent self-improvement system
            </p>
          </div>
          <span className="text-teal-600 flex-shrink-0 ml-2 min-w-[20px] text-center">
            {showIntelligence ? "▲" : "▼"}
          </span>
        </button>

        {showIntelligence && (
          <div className="divide-y divide-teal-900/40">
            {INTELLIGENCE_FILES.map((item, i) => (
              <div
                key={i}
                className={`bg-teal-950/10 ${isMobile ? "px-3 py-3" : "px-5 py-3"}`}
              >
                <p className={`text-teal-300 font-mono font-medium ${isMobile ? "text-xs break-all" : "text-xs"}`}>
                  {item.file}
                </p>
                <p className={`text-gray-400 mt-1 ${isMobile ? "text-xs leading-relaxed" : "text-xs"}`}>
                  {item.purpose}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}