"""
pipeline/quality/security_scanner.py
Security scanning on the generated codebase before ZIP assembly.

Two scans:
  1. pip-audit  — checks generated requirements.txt against PyPI vulnerability database
  2. detect-secrets — scans all Python files for accidentally hardcoded secrets

Both tools are open-source and free. Results are compiled into SECURITY_REPORT.txt
which is included in every generated ZIP package.

Neither scan blocks packaging — a failing scan results in the issues being
documented in SECURITY_REPORT.txt with remediation guidance.
"""

import os
import subprocess
import tempfile
from typing import Optional

from loguru import logger


async def run_security_scan(generated_files: dict[str, str]) -> str:
    """
    Run all security scans on generated files.

    Returns:
        Complete SECURITY_REPORT.txt content as a string.
    """
    report_sections: list[str] = [
        "SECURITY REPORT — Generated by The Forge",
        "=" * 50,
        "",
    ]

    # Scan 1: Dependency vulnerabilities
    pip_audit_result = await _run_pip_audit(generated_files.get("requirements.txt", ""))
    report_sections.append("DEPENDENCY VULNERABILITY SCAN (pip-audit):")
    report_sections.append(pip_audit_result)
    report_sections.append("")

    # Scan 2: Hardcoded secrets detection
    secrets_result = await _run_detect_secrets(generated_files)
    report_sections.append("HARDCODED SECRETS SCAN (detect-secrets):")
    report_sections.append(secrets_result)
    report_sections.append("")

    # Scan 3: Common security anti-patterns (static check, no external tool needed)
    patterns_result = _check_security_patterns(generated_files)
    report_sections.append("SECURITY PATTERN CHECK:")
    report_sections.append(patterns_result)

    return "\n".join(report_sections)


async def _run_pip_audit(requirements_content: str) -> str:
    """Run pip-audit on the generated requirements.txt."""
    if not requirements_content.strip():
        return "SKIPPED — No requirements.txt in generated package."

    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".txt", delete=False
        ) as tmp:
            tmp.write(requirements_content)
            tmp_path = tmp.name

        result = subprocess.run(
            ["pip-audit", "-r", tmp_path, "--format", "columns"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        os.unlink(tmp_path)

        if result.returncode == 0:
            return "PASS — No known vulnerabilities found in generated requirements."
        else:
            output = result.stdout or result.stderr
            return f"ISSUES FOUND:\n{output[:1500]}\n\nRemediation: Update affected packages to patched versions."

    except FileNotFoundError:
        return "SKIPPED — pip-audit not installed (install with: pip install pip-audit)."
    except subprocess.TimeoutExpired:
        return "SKIPPED — pip-audit timed out after 120 seconds."
    except Exception as exc:
        logger.warning(f"pip-audit failed: {exc}")
        return f"SKIPPED — Scan error: {exc}"


async def _run_detect_secrets(generated_files: dict[str, str]) -> str:
    """Run detect-secrets on all generated Python files."""
    python_files = {
        path: content
        for path, content in generated_files.items()
        if path.endswith(".py") and content
    }

    if not python_files:
        return "SKIPPED — No Python files to scan."

    try:
        import detect_secrets.core.scan as ds_scan
        from detect_secrets import SecretsCollection
        from detect_secrets.settings import default_settings

        issues: list[str] = []
        with default_settings():
            for path, content in python_files.items():
                # Write to temp file for scanning
                with tempfile.NamedTemporaryFile(
                    mode="w", suffix=".py", delete=False
                ) as tmp:
                    tmp.write(content)
                    tmp_path = tmp.name

                try:
                    result = subprocess.run(
                        ["detect-secrets", "scan", tmp_path],
                        capture_output=True,
                        text=True,
                        timeout=30,
                    )
                    if '"results":' in result.stdout:
                        import json
                        scan_result = json.loads(result.stdout)
                        if scan_result.get("results"):
                            for findings in scan_result["results"].values():
                                for finding in findings:
                                    issues.append(
                                        f"  {path} line {finding.get('line_number', '?')}: "
                                        f"{finding.get('type', 'unknown secret type')}"
                                    )
                finally:
                    os.unlink(tmp_path)

        if issues:
            return (
                f"ISSUES FOUND ({len(issues)} potential secrets):\n"
                + "\n".join(issues)
                + "\n\nRemediation: Move all values to environment variables. Never hardcode secrets."
            )
        return "PASS — No hardcoded secrets detected."

    except FileNotFoundError:
        # detect-secrets not installed — fall back to simple pattern check
        return _simple_secrets_scan(python_files)
    except Exception as exc:
        logger.warning(f"detect-secrets scan failed: {exc}")
        return f"SKIPPED — Scan error: {exc}"


def _simple_secrets_scan(python_files: dict[str, str]) -> str:
    """
    Simple regex-based secrets scan as fallback when detect-secrets is unavailable.
    Checks for common hardcoded secret patterns.
    """
    import re

    patterns = [
        (re.compile(r'sk-ant-api03-[A-Za-z0-9\-_]{40,}'), "Anthropic API key"),
        (re.compile(r'sk-[A-Za-z0-9]{48,}'), "OpenAI API key"),
        (re.compile(r'tvly-[A-Za-z0-9]{20,}'), "Tavily API key"),
        (re.compile(r'password\s*=\s*["\'][^"\']+["\']'), "Hardcoded password"),
        (re.compile(r'secret\s*=\s*["\'][^"\']{8,}["\']', re.IGNORECASE), "Hardcoded secret"),
    ]

    issues: list[str] = []
    for path, content in python_files.items():
        for line_num, line in enumerate(content.split("\n"), 1):
            if line.strip().startswith("#"):
                continue
            for pattern, label in patterns:
                if pattern.search(line):
                    issues.append(f"  {path}:{line_num}: Possible {label}")

    if issues:
        return (
            f"POTENTIAL ISSUES ({len(issues)}):\n"
            + "\n".join(issues)
            + "\n\nRemediation: Use os.environ['KEY'] or pydantic-settings."
        )
    return "PASS — No obvious hardcoded secrets detected (pattern-based scan)."


def _check_security_patterns(generated_files: dict[str, str]) -> str:
    """Check for common security anti-patterns in the generated codebase."""
    import re

    issues: list[str] = []
    python_files = {
        path: content
        for path, content in generated_files.items()
        if path.endswith(".py") and content
    }

    anti_patterns = [
        (re.compile(r'eval\s*\('), "Use of eval() — potential code injection"),
        (re.compile(r'exec\s*\('), "Use of exec() — potential code injection"),
        (re.compile(r'pickle\.loads\('), "Use of pickle.loads() — unsafe deserialization"),
        (re.compile(r'os\.system\('), "Use of os.system() — use subprocess instead"),
        (re.compile(r'shell=True'), "subprocess with shell=True — potential injection"),
        (re.compile(r'DEBUG\s*=\s*True'), "DEBUG=True in production code"),
    ]

    for path, content in python_files.items():
        for pattern, description in anti_patterns:
            if pattern.search(content):
                issues.append(f"  {path}: {description}")

    if issues:
        return "WARNINGS:\n" + "\n".join(issues)
    return "PASS — No common security anti-patterns detected."
